### ISSUE TITLE
Avoid deleting of App title

### ISSUE THREAD

**Issue by Cadesh** [evlnyng/CornellNote#6]
Currently when a user clicks clear the Main Title "MY NOTES" disappears, I believe this should only happen to the notes in the notes area.

**Comment by evlnyng** [comment]
I apologize for the confusion - each section is meant to be editable, so that the user has complete control over every aspect of the notepad. This gives me the idea that I should have the notepad clear to the default text as opposed to just an empty page, just to make it clear to the user, so thank you very much for the input!
